export const routesConfig = {
  home: 'home',
  artists: 'artists',
  artist: 'artist',
  clubs: 'clubs',
  club: 'club',
  search: 'search',
  tracks: 'tracks',
  track: 'track',
  sets: 'sets',
  set: 'set',
  auth: 'auth',
  login: 'login',
  register: 'register',
  account: 'account',
  edit: 'edit',
  styles: 'styles',
  users: 'users',
  one: 'one'
};
