export const routesConfig = {
  account: 'account',
  accountEdit: 'account/edit',
  artist: 'artists/profile/:slug',
  artists: 'artists',
  artistAdmin: 'admin/artists/one/:id',
  artistsAdmin: 'admin/artists',
  artistsFilter: 'artists/filter/:filterKey/:filterValue',
  auth: 'auth',
  club: 'club',
  clubs: 'clubs',
  edit: 'edit',
  home: 'home',
  login: 'login',
  media: 'media',
  one: 'one',
  register: 'register',
  search: 'search',
  set: 'set/:id',
  sets: 'sets',
  setsFilter: `sets/:filterKey/:filterValue`,
  styles: 'styles',
  track: 'track',
  tracks: 'tracks',
  users: 'users',
};
